M48
; DRILL file {KiCad 6.0.2-378541a8eb~116~ubuntu20.04.1} date Fri Feb 25 19:51:51 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-02-25T19:51:51+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.2-378541a8eb~116~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
%
G90
G05
T1
X126.205Y-121.834
X138.938Y-121.877
T0
M30
