M48
; DRILL file {KiCad 6.0.1-79c1e3a40b~116~ubuntu18.04.1} date Tue Feb  8 09:12:31 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-02-08T09:12:31+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.1-79c1e3a40b~116~ubuntu18.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
%
G90
G05
T1
X126.205Y-121.834
X138.938Y-121.877
T0
M30
