M48
; DRILL file {KiCad 6.0.4-6f826c9f35~116~ubuntu18.04.1} date Tue Apr 26 12:07:34 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-04-26T12:07:34+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.4-6f826c9f35~116~ubuntu18.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.200
%
G90
G05
T1
X144.265Y-63.572
X144.265Y-72.572
T2
X138.144Y-84.638
T0
M30
